version: '3.8'
services:
  adminjs:
    container_name: adminjs
    build:
      context: ./adminjs
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    volumes:
       - ./adminjs:/usr/src/app/adminjs
       - /usr/src/app/adminjs/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123#
      MYSQL_DATABASE: adminjs
      MYSQL_USER: adminjs
      MYSQL_PASSWORD: Password123#
    command: --max_allowed_packet=1073741824
    volumes:
      - adminjs-mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  adminjs-mysql-data: